plugins {
    id 'com.android.application'
}

android {
    compileSdk = 37
    defaultConfig {
        applicationId = "com.wambo.andy.wambo"
        minSdk = 23
        targetSdk = 37
        versionCode = 6
        versionName = "1.4"
    }
    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            shrinkResources = true
            optimization {
                enable = true // Enables code and resource optimizations.
            }
        }
    }
    namespace = 'com.wambo.andy.wambo'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
}

allprojects {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
