plugins {
    id 'com.android.application'
}

android {
    compileSdk = 37
    defaultConfig {
        applicationId = "com.wambo.andy.wambo"
        minSdk = 14
        targetSdk = 37
        versionCode = 5
        versionName = "1.3"
    }
    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            shrinkResources = true
        }
    }
    namespace = 'com.wambo.andy.wambo'
}

dependencies {

}

allprojects {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.deprecation = true
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
